name: Build Production Firmware

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Install
         run: |
          sudo apt -y update
          sudo apt -y install gcc-arm-none-eabi
       - name: Update Submodules
         run: |
          git submodule update --init --recursive

       - name: Clean
         run: |
          cd firmware/
          make clean

       - name: Build Production Firmware
         run: |
          make